name: Pull Request checks

on:
  workflow_call:
    inputs:
      configs-path:
        description: 'Set this to override the linting configs with the ones in this folder. 
        The structure inside of the folder must be the same as the one in this repository.'
        required: false
        type: string
        default: '._linting' # Use the configs from this repository (separate checkout)
      excluded-directories:
        description: 'List of directories to exclude (JSON), empty = none'
        required: false
        type: string
        default: '[]'

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    name: checkstyle
    steps:
      - name: Checkout the commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changedFiles
        uses: tj-actions/changed-files@v34
        with:
          sha: ${{ github.event.pull_request.head.sha }}
          base_sha: ${{ github.event.pull_request.base.sha }}

      - name: Setting up java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # Needed to have access to the linter files
      - name: Checkout this repository
        uses: actions/checkout@v3
        with:
          repository: pmagentur/linting-java
          path: ._linting

      - name: Linting with checkstyle
        id: linter
        uses: pmagentur/linting-action@v0.4
        with:
          changed-files: ${{ steps.changedFiles.outputs.all_changed_files }}
          linter-command: "java -jar ._linting/checkstyle/checkstyle-10.3.3-all.jar -c ${{ inputs.configs-path }}/checkstyle/config.xml {files}"
          parse-pattern: '\[(?<level>[^\]]+)\] (?<file>[^:]+):(?<line>\d+)(?::(?<column>\d+))?: (?<message>.+) \[(?<ruleName>[^\]]+)\]'
          relevant-file-endings: '["java"]'
          excluded-directories: ${{ inputs.excluded-directories }}

      - name: Add Annotations
        uses: pmagentur/linting-annotations@v0.1
        if: failure() && steps.linter.outputs.annotations != ''
        with:
          commitSha: ${{ github.event.pull_request.head.sha }}
          checkName: 'Java Linting'
          annotations: ${{ steps.linter.outputs.annotations }}
